### ISSUE TITLE
Clean up variables list command output

### ISSUE THREAD

**Issue by Baggerone** [silinternational/tfc-ops#30]
`variables list -v idphelp -o abcd` probably doesn't need to output the workspaces that have no match.

In other words, don't output the lines that say `foo has no matching variables.`

Also, for found matches, output the workspace name on the same line as the variable information.

**Comment by Schparky** [comment]
@fillup there are two separate things suggested here. I think the PR only addresses the first. Was the other fixed in a separate PR?
